Map<String, Map<String, String>> countryData = {
  'af': {'name': 'Afghanistan', 'dial_code': '+93'},
  'al': {'name': 'Albania', 'dial_code': '+355'},
  'dz': {'name': 'Algeria', 'dial_code': '+213'},
  'as': {'name': 'American Samoa', 'dial_code': '+1-684'},
  'ad': {'name': 'Andorra', 'dial_code': '+376'},
  'ao': {'name': 'Angola', 'dial_code': '+244'},
  'ar': {'name': 'Argentina', 'dial_code': '+54'},
  'am': {'name': 'Armenia', 'dial_code': '+374'},
  'aw': {'name': 'Aruba', 'dial_code': '+297'},
  'au': {'name': 'Australia', 'dial_code': '+61'},
  'at': {'name': 'Austria', 'dial_code': '+43'},
  'az': {'name': 'Azerbaijan', 'dial_code': '+994'},
  'bs': {'name': 'Bahamas', 'dial_code': '+1-242'},
  'bh': {'name': 'Bahrain', 'dial_code': '+973'},
  'bd': {'name': 'Bangladesh', 'dial_code': '+880'},
  'bb': {'name': 'Barbados', 'dial_code': '+1-246'},
  'by': {'name': 'Belarus', 'dial_code': '+375'},
  'be': {'name': 'Belgium', 'dial_code': '+32'},
  'bz': {'name': 'Belize', 'dial_code': '+501'},
  'bj': {'name': 'Benin', 'dial_code': '+229'},
  'bt': {'name': 'Bhutan', 'dial_code': '+975'},
  'bo': {'name': 'Bolivia', 'dial_code': '+591'},
  'ba': {'name': 'Bosnia and Herzegovina', 'dial_code': '+387'},
  'bw': {'name': 'Botswana', 'dial_code': '+267'},
  'br': {'name': 'Brazil', 'dial_code': '+55'},
  'bn': {'name': 'Brunei Darussalam', 'dial_code': '+673'},
  'bg': {'name': 'Bulgaria', 'dial_code': '+359'},
  'bf': {'name': 'Burkina Faso', 'dial_code': '+226'},
  'bi': {'name': 'Burundi', 'dial_code': '+257'},
  'kh': {'name': 'Cambodia', 'dial_code': '+855'},
  'cm': {'name': 'Cameroon', 'dial_code': '+237'},
  'ca': {'name': 'Canada', 'dial_code': '+1'},
  'cv': {'name': 'Cape Verde', 'dial_code': '+238'},
  'ky': {'name': 'Cayman Islands', 'dial_code': '+1-345'},
  'cf': {'name': 'Central African Republic', 'dial_code': '+236'},
  'td': {'name': 'Chad', 'dial_code': '+235'},
  'cl': {'name': 'Chile', 'dial_code': '+56'},
  'cn': {'name': 'China', 'dial_code': '+86'},
  'co': {'name': 'Colombia', 'dial_code': '+57'},
  'km': {'name': 'Comoros', 'dial_code': '+269'},
  'cg': {'name': 'Congo', 'dial_code': '+242'},
  'cd': {'name': 'Congo (Democratic Republic)', 'dial_code': '+243'},
  'cr': {'name': 'Costa Rica', 'dial_code': '+506'},
  'ci': {'name': 'Côte d\'Ivoire', 'dial_code': '+225'},
  'hr': {'name': 'Croatia', 'dial_code': '+385'},
  'cu': {'name': 'Cuba', 'dial_code': '+53'},
  'cy': {'name': 'Cyprus', 'dial_code': '+357'},
  'cz': {'name': 'Czech Republic', 'dial_code': '+420'},
  'dk': {'name': 'Denmark', 'dial_code': '+45'},
  'dj': {'name': 'Djibouti', 'dial_code': '+253'},
  'dm': {'name': 'Dominica', 'dial_code': '+1-767'},
  'do': {'name': 'Dominican Republic', 'dial_code': '+1-809'},
  'ec': {'name': 'Ecuador', 'dial_code': '+593'},
  'eg': {'name': 'Egypt', 'dial_code': '+20'},
  'sv': {'name': 'El Salvador', 'dial_code': '+503'},
  'gq': {'name': 'Equatorial Guinea', 'dial_code': '+240'},
  'er': {'name': 'Eritrea', 'dial_code': '+291'},
  'ee': {'name': 'Estonia', 'dial_code': '+372'},
  'et': {'name': 'Ethiopia', 'dial_code': '+251'},
  'fk': {'name': 'Falkland Islands', 'dial_code': '+500'},
  'fo': {'name': 'Faroe Islands', 'dial_code': '+298'},
  'fj': {'name': 'Fiji', 'dial_code': '+679'},
  'fi': {'name': 'Finland', 'dial_code': '+358'},
  'fr': {'name': 'France', 'dial_code': '+33'},
  'gf': {'name': 'French Guiana', 'dial_code': '+594'},
  'pf': {'name': 'French Polynesia', 'dial_code': '+689'},
  'ga': {'name': 'Gabon', 'dial_code': '+241'},
  'gb': {'name': 'United Kingdom', 'dial_code': '+44'},
  'ge': {'name': 'Georgia', 'dial_code': '+995'},
  'gh': {'name': 'Ghana', 'dial_code': '+233'},
  'gi': {'name': 'Gibraltar', 'dial_code': '+350'},
  'gr': {'name': 'Greece', 'dial_code': '+30'},
  'gl': {'name': 'Greenland', 'dial_code': '+299'},
  'gd': {'name': 'Grenada', 'dial_code': '+1-473'},
  'gp': {'name': 'Guadeloupe', 'dial_code': '+590'},
  'gu': {'name': 'Guam', 'dial_code': '+1-671'},
  'gt': {'name': 'Guatemala', 'dial_code': '+502'},
  'gn': {'name': 'Guinea', 'dial_code': '+224'},
  'gw': {'name': 'Guinea-Bissau', 'dial_code': '+245'},
  'gy': {'name': 'Guyana', 'dial_code': '+592'},
  'ht': {'name': 'Haiti', 'dial_code': '+509'},
  'hn': {'name': 'Honduras', 'dial_code': '+504'},
  'hk': {'name': 'Hong Kong', 'dial_code': '+852'},
  'hu': {'name': 'Hungary', 'dial_code': '+36'},
  'is': {'name': 'Iceland', 'dial_code': '+354'},
  'in': {'name': 'India', 'dial_code': '+91'},
  'id': {'name': 'Indonesia', 'dial_code': '+62'},
  'ir': {'name': 'Iran', 'dial_code': '+98'},
  'iq': {'name': 'Iraq', 'dial_code': '+964'},
  'ie': {'name': 'Ireland', 'dial_code': '+353'},
  'il': {'name': 'Israel', 'dial_code': '+972'},
  'it': {'name': 'Italy', 'dial_code': '+39'},
  'jm': {'name': 'Jamaica', 'dial_code': '+1-876'},
  'jp': {'name': 'Japan', 'dial_code': '+81'},
  'jo': {'name': 'Jordan', 'dial_code': '+962'},
  'kz': {'name': 'Kazakhstan', 'dial_code': '+7'},
  'ke': {'name': 'Kenya', 'dial_code': '+254'},
  'ki': {'name': 'Kiribati', 'dial_code': '+686'},
  'kw': {'name': 'Kuwait', 'dial_code': '+965'},
  'kg': {'name': 'Kyrgyzstan', 'dial_code': '+996'},
  'la': {'name': 'Laos', 'dial_code': '+856'},
  'lv': {'name': 'Latvia', 'dial_code': '+371'},
  'lb': {'name': 'Lebanon', 'dial_code': '+961'},
  'ls': {'name': 'Lesotho', 'dial_code': '+266'},
  'lr': {'name': 'Liberia', 'dial_code': '+231'},
  'ly': {'name': 'Libya', 'dial_code': '+218'},
  'li': {'name': 'Liechtenstein', 'dial_code': '+423'},
  'lt': {'name': 'Lithuania', 'dial_code': '+370'},
  'lu': {'name': 'Luxembourg', 'dial_code': '+352'},
  'mo': {'name': 'Macao', 'dial_code': '+853'},
  'mk': {'name': 'North Macedonia', 'dial_code': '+389'},
  'mg': {'name': 'Madagascar', 'dial_code': '+261'},
  'mw': {'name': 'Malawi', 'dial_code': '+265'},
  'my': {'name': 'Malaysia', 'dial_code': '+60'},
  'mv': {'name': 'Maldives', 'dial_code': '+960'},
  'ml': {'name': 'Mali', 'dial_code': '+223'},
  'mt': {'name': 'Malta', 'dial_code': '+356'},
  'mh': {'name': 'Marshall Islands', 'dial_code': '+692'},
  'mq': {'name': 'Martinique', 'dial_code': '+596'},
  'mr': {'name': 'Mauritania', 'dial_code': '+222'},
  'mu': {'name': 'Mauritius', 'dial_code': '+230'},
  'yt': {'name': 'Mayotte', 'dial_code': '+262'},
  'mx': {'name': 'Mexico', 'dial_code': '+52'},
  'fm': {'name': 'Micronesia', 'dial_code': '+691'},
  'md': {'name': 'Moldova', 'dial_code': '+373'},
  'mc': {'name': 'Monaco', 'dial_code': '+377'},
  'mn': {'name': 'Mongolia', 'dial_code': '+976'},
  'me': {'name': 'Montenegro', 'dial_code': '+382'},
  'ms': {'name': 'Montserrat', 'dial_code': '+1-664'},
  'ma': {'name': 'Morocco', 'dial_code': '+212'},
  'mz': {'name': 'Mozambique', 'dial_code': '+258'},
  'mm': {'name': 'Myanmar', 'dial_code': '+95'},
  'na': {'name': 'Namibia', 'dial_code': '+264'},
  'nr': {'name': 'Nauru', 'dial_code': '+674'},
  'np': {'name': 'Nepal', 'dial_code': '+977'},
  'nl': {'name': 'Netherlands', 'dial_code': '+31'},
  'nc': {'name': 'New Caledonia', 'dial_code': '+687'},
  'nz': {'name': 'New Zealand', 'dial_code': '+64'},
  'ni': {'name': 'Nicaragua', 'dial_code': '+505'},
  'ne': {'name': 'Niger', 'dial_code': '+227'},
  'ng': {'name': 'Nigeria', 'dial_code': '+234'},
  'no': {'name': 'Norway', 'dial_code': '+47'},
  'om': {'name': 'Oman', 'dial_code': '+968'},
  'pk': {'name': 'Pakistan', 'dial_code': '+92'},
  'pw': {'name': 'Palau', 'dial_code': '+680'},
  'pa': {'name': 'Panama', 'dial_code': '+507'},
  'pg': {'name': 'Papua New Guinea', 'dial_code': '+675'},
  'py': {'name': 'Paraguay', 'dial_code': '+595'},
  'pe': {'name': 'Peru', 'dial_code': '+51'},
  'ph': {'name': 'Philippines', 'dial_code': '+63'},
  'pl': {'name': 'Poland', 'dial_code': '+48'},
  'pt': {'name': 'Portugal', 'dial_code': '+351'},
  'pr': {'name': 'Puerto Rico', 'dial_code': '+1-787'},
  'qa': {'name': 'Qatar', 'dial_code': '+974'},
  'ro': {'name': 'Romania', 'dial_code': '+40'},
  'ru': {'name': 'Russia', 'dial_code': '+7'},
  'rw': {'name': 'Rwanda', 'dial_code': '+250'},
  're': {'name': 'Réunion', 'dial_code': '+262'},
  'sh': {'name': 'Saint Helena', 'dial_code': '+290'},
  'kn': {'name': 'Saint Kitts and Nevis', 'dial_code': '+1-869'},
  'lc': {'name': 'Saint Lucia', 'dial_code': '+1-758'},
  'pm': {'name': 'Saint Pierre and Miquelon', 'dial_code': '+508'},
  'vc': {'name': 'Saint Vincent and the Grenadines', 'dial_code': '+1-784'},
  'ws': {'name': 'Samoa', 'dial_code': '+685'},
  'sm': {'name': 'San Marino', 'dial_code': '+378'},
  'sa': {'name': 'Saudi Arabia', 'dial_code': '+966'},
  'sn': {'name': 'Senegal', 'dial_code': '+221'},
  'rs': {'name': 'Serbia', 'dial_code': '+381'},
  'sc': {'name': 'Seychelles', 'dial_code': '+248'},
  'sl': {'name': 'Sierra Leone', 'dial_code': '+232'},
  'sg': {'name': 'Singapore', 'dial_code': '+65'},
  'sx': {'name': 'Sint Maarten', 'dial_code': '+1-721'},
  'sk': {'name': 'Slovakia', 'dial_code': '+421'},
  'si': {'name': 'Slovenia', 'dial_code': '+386'},
  'sb': {'name': 'Solomon Islands', 'dial_code': '+677'},
  'so': {'name': 'Somalia', 'dial_code': '+252'},
  'za': {'name': 'South Africa', 'dial_code': '+27'},
  'kr': {'name': 'South Korea', 'dial_code': '+82'},
  'ss': {'name': 'South Sudan', 'dial_code': '+211'},
  'es': {'name': 'Spain', 'dial_code': '+34'},
  'lk': {'name': 'Sri Lanka', 'dial_code': '+94'},
  'sd': {'name': 'Sudan', 'dial_code': '+249'},
  'sr': {'name': 'Suriname', 'dial_code': '+597'},
  'sz': {'name': 'Swaziland', 'dial_code': '+268'},
  'se': {'name': 'Sweden', 'dial_code': '+46'},
  'ch': {'name': 'Switzerland', 'dial_code': '+41'},
  'sy': {'name': 'Syria', 'dial_code': '+963'},
  'tw': {'name': 'Taiwan', 'dial_code': '+886'},
  'tj': {'name': 'Tajikistan', 'dial_code': '+992'},
  'tz': {'name': 'Tanzania', 'dial_code': '+255'},
  'th': {'name': 'Thailand', 'dial_code': '+66'},
  'tl': {'name': 'Timor-Leste', 'dial_code': '+670'},
  'tg': {'name': 'Togo', 'dial_code': '+228'},
  'tk': {'name': 'Tokelau', 'dial_code': '+690'},
  'to': {'name': 'Tonga', 'dial_code': '+676'},
  'tt': {'name': 'Trinidad and Tobago', 'dial_code': '+1-868'},
  'tn': {'name': 'Tunisia', 'dial_code': '+216'},
  'tr': {'name': 'Turkey', 'dial_code': '+90'},
  'tm': {'name': 'Turkmenistan', 'dial_code': '+993'},
  'tc': {'name': 'Turks and Caicos Islands', 'dial_code': '+1-649'},
  'tv': {'name': 'Tuvalu', 'dial_code': '+688'},
  'ug': {'name': 'Uganda', 'dial_code': '+256'},
  'ua': {'name': 'Ukraine', 'dial_code': '+380'},
  'ae': {'name': 'United Arab Emirates', 'dial_code': '+971'},
  'us': {'name': 'United States', 'dial_code': '+1'},
  'uy': {'name': 'Uruguay', 'dial_code': '+598'},
  'uz': {'name': 'Uzbekistan', 'dial_code': '+998'},
  'vu': {'name': 'Vanuatu', 'dial_code': '+678'},
  'va': {'name': 'Vatican City', 'dial_code': '+379'},
  've': {'name': 'Venezuela', 'dial_code': '+58'},
  'vn': {'name': 'Vietnam', 'dial_code': '+84'},
  'wf': {'name': 'Wallis and Futuna', 'dial_code': '+681'},
  'eh': {'name': 'Western Sahara', 'dial_code': '+212'},
  'ye': {'name': 'Yemen', 'dial_code': '+967'},
  'zm': {'name': 'Zambia', 'dial_code': '+260'},
  'zw': {'name': 'Zimbabwe', 'dial_code': '+263'},
};
