List<Map<String, dynamic>> languageData = [
  {"code": "ab", "name": "Abkhazian", "nativeName": "Aҧсуа"},
  {"code": "aa", "name": "Afar", "nativeName": "Afaraf"},
  {"code": "af", "name": "Afrikaans", "nativeName": "Afrikaans"},
  {"code": "ak", "name": "Akan", "nativeName": "Akan"},
  {"code": "sq", "name": "Albanian", "nativeName": "Shqip"},
  {"code": "am", "name": "Amharic", "nativeName": "አማርኛ"},
  {"code": "ar", "name": "Arabic", "nativeName": "العربية"},
  {"code": "an", "name": "Aragonese", "nativeName": "Aragonés"},
  {"code": "hy", "name": "Armenian", "nativeName": "Հայերեն"},
  {"code": "as", "name": "Assamese", "nativeName": "অসমীয়া"},
  {"code": "av", "name": "Avaric", "nativeName": "Aвар мацӀ, магӀарул мацӀ"},
  {"code": "ae", "name": "Avestan", "nativeName": "Avesta"},
  {"code": "ay", "name": "Aymara", "nativeName": "Aymar aru"},
  {"code": "az", "name": "Azerbaijani", "nativeName": "Azərbaycan dili"},
  {"code": "bm", "name": "Bambara", "nativeName": "Bamanankan"},
  {"code": "ba", "name": "Bashkir", "nativeName": "башҡорт теле"},
  {"code": "eu", "name": "Basque", "nativeName": "Euskara, euskera"},
  {"code": "be", "name": "Belarusian", "nativeName": "Беларуская"},
  {"code": "bn", "name": "Bengali", "nativeName": "বাংলা"},
  {"code": "bh", "name": "Bihari Languages", "nativeName": "भोजपुरी"},
  {"code": "bi", "name": "Bislama", "nativeName": "Bislama"},
  {"code": "nb", "name": "Norwegian Bokmål", "nativeName": "Norsk bokmål"},
  {"code": "bs", "name": "Bosnian", "nativeName": "Bosanski jezik"},
  {"code": "br", "name": "Breton", "nativeName": "Brezhoneg"},
  {"code": "bg", "name": "Bulgarian", "nativeName": "български език"},
  {"code": "my", "name": "Burmese", "nativeName": "ဗမာစာ"},
  {"code": "ca", "name": "Catalan", "nativeName": "Català"},
  {"code": "km", "name": "Central Khmer", "nativeName": "ភាសាខ្មែរ"},
  {"code": "ch", "name": "Chamorro", "nativeName": "Chamoru"},
  {"code": "ce", "name": "Chechen", "nativeName": "нохчийн мотт"},
  {"code": "ny", "name": "Chewa (Nyanja)", "nativeName": "chiCheŵa, chinyanja"},
  {"code": "zh", "name": "Chinese", "nativeName": "中文 (Zhōngwén), 汉语, 漢語"},
  {"code": "zh_Hans", "name": "Chinese (Simplified)", "nativeName": "简体中文"},
  {"code": "zh_Hant", "name": "Chinese (Traditional)", "nativeName": "中國傳統"},
  {"code": "cu", "name": "Church Slavonic", "nativeName": "ѩзыкъ словѣньскъ"},
  {"code": "cv", "name": "Chuvash", "nativeName": "чӑваш чӗлхи"},
  {"code": "kw", "name": "Cornish", "nativeName": "Kernewek"},
  {"code": "co", "name": "Corsican", "nativeName": "Corsu, lingua corsa"},
  {"code": "cr", "name": "Cree", "nativeName": "ᓀᐦᐃᔭᐍᐏᐣ"},
  {"code": "hr", "name": "Croatian", "nativeName": "Hrvatski"},
  {"code": "cs", "name": "Czech", "nativeName": "česky, čeština"},
  {"code": "da", "name": "Danish", "nativeName": "Dansk"},
  {"code": "dv", "name": "Dhivehi", "nativeName": "ދިވެހި"},
  {"code": "nl", "name": "Dutch", "nativeName": "Nederlands, Vlaams"},
  {"code": "dz", "name": "Dzongkha", "nativeName": "རྫོང་ཁ"},
  {"code": "en", "name": "English", "nativeName": "English"},
  {"code": "eo", "name": "Esperanto", "nativeName": "Esperanto"},
  {"code": "et", "name": "Estonian", "nativeName": "Eesti, eesti keel"},
  {"code": "ee", "name": "Ewe", "nativeName": "Eʋegbe"},
  {"code": "fo", "name": "Faroese", "nativeName": "Føroyskt"},
  {"code": "fj", "name": "Fijian", "nativeName": "Vosa Vakaviti"},
  {"code": "fi", "name": "Finnish", "nativeName": "Suomi, suomen kieli"},
  {"code": "fr", "name": "French", "nativeName": "Français, langue française"},
  {"code": "ff", "name": "Fulah", "nativeName": "Fulfulde, Pulaar, Pular"},
  {"code": "gd", "name": "Gaelic", "nativeName": "Gàidhlig"},
  {"code": "gl", "name": "Galician", "nativeName": "Galego"},
  {"code": "lg", "name": "Ganda", "nativeName": "Luganda"},
  {"code": "ka", "name": "Georgian", "nativeName": "ქართული"},
  {"code": "de", "name": "German", "nativeName": "Deutsch"},
  {"code": "el", "name": "Greek, Modern (1453-)", "nativeName": "Ελληνικά"},
  {"code": "gn", "name": "Guarani", "nativeName": "Avañeẽ"},
  {"code": "gu", "name": "Gujarati", "nativeName": "ગુજરાતી"},
  {"code": "ht", "name": "Haitian", "nativeName": "Kreyòl ayisyen"},
  {"code": "ha", "name": "Hausa", "nativeName": "Hausa, هَوُسَ"},
  {"code": "he", "name": "Hebrew", "nativeName": "עברית"},
  {"code": "hz", "name": "Herero", "nativeName": "Otjiherero"},
  {"code": "hi", "name": "Hindi", "nativeName": "हिन्दी, हिंदी"},
  {"code": "ho", "name": "Hiri Motu", "nativeName": "Hiri Motu"},
  {"code": "hu", "name": "Hungarian", "nativeName": "Magyar"},
  {"code": "is", "name": "Icelandic", "nativeName": "Íslenska"},
  {"code": "io", "name": "Ido", "nativeName": "Ido"},
  {"code": "ig", "name": "Igbo", "nativeName": "Asụsụ Igbo"},
  {"code": "id", "name": "Indonesian", "nativeName": "Bahasa Indonesia"},
  {"code": "ia", "name": "Interlingua", "nativeName": "Interlingua"},
  {"code": "ie", "name": "Interlingue", "nativeName": "Interlingue"},
  {"code": "iu", "name": "Inuktitut", "nativeName": "ᐃᓄᒃᑎᑐᑦ"},
  {"code": "ik", "name": "Inupiaq", "nativeName": "Iñupiaq, Iñupiatun"},
  {"code": "ga", "name": "Irish", "nativeName": "Gaeilge"},
  {"code": "it", "name": "Italian", "nativeName": "Italiano"},
  {"code": "ja", "name": "Japanese", "nativeName": "日本語 (にほんご／にっぽんご)"},
  {"code": "jv", "name": "Javanese", "nativeName": "Basa Jawa"},
  {
    "code": "kl",
    "name": "Kalaallisut",
    "nativeName": "kalaallisut, kalaallit oqaasii"
  },
  {"code": "kn", "name": "Kannada", "nativeName": "ಕನ್ನಡ"},
  {"code": "kr", "name": "Kanuri", "nativeName": "Kanuri"},
  {"code": "ks", "name": "Kashmiri", "nativeName": "कश्मीरी, كشميري‎"},
  {"code": "kk", "name": "Kazakh", "nativeName": "Қазақ тілі"},
  {"code": "ki", "name": "Kikuyu", "nativeName": "Gĩkũyũ"},
  {"code": "rw", "name": "Kinyarwanda", "nativeName": "Ikinyarwanda"},
  {"code": "ky", "name": "Kirghiz", "nativeName": "кыргыз тили"},
  {"code": "kv", "name": "Komi", "nativeName": "коми кыв"},
  {"code": "kg", "name": "Kongo", "nativeName": "KiKongo"},
  {"code": "ko", "name": "Korean", "nativeName": "한국어 (韓國語), 조선말 (朝鮮語)"},
  {"code": "kj", "name": "Kuanyama", "nativeName": "Kuanyama"},
  {"code": "ku", "name": "Kurdish", "nativeName": "Kurdî, كوردی‎"},
  {"code": "lo", "name": "Lao", "nativeName": "ພາສາລາວ"},
  {"code": "la", "name": "Latin", "nativeName": "latine, Lingua latina"},
  {"code": "lv", "name": "Latvian", "nativeName": "Latviešu valoda"},
  {"code": "li", "name": "Limburgan", "nativeName": "Limburgs"},
  {"code": "ln", "name": "Lingala", "nativeName": "Lingála"},
  {"code": "lt", "name": "Lithuanian", "nativeName": "lietuvių kalba"},
  {"code": "lu", "name": "Luba-Katanga", "nativeName": "Luba-katanga"},
  {"code": "lb", "name": "Luxembourgish", "nativeName": "Lëtzebuergesch"},
  {"code": "mk", "name": "Macedonian", "nativeName": "македонски јазик"},
  {"code": "mg", "name": "Malagasy", "nativeName": "Malagasy fiteny"},
  {"code": "ms", "name": "Malay", "nativeName": "Bahasa Melayu, بهاس ملايو‎"},
  {"code": "ml", "name": "Malayalam", "nativeName": "മലയാളം"},
  {"code": "mt", "name": "Maltese", "nativeName": "Malti"},
  {"code": "gv", "name": "Manx", "nativeName": "Gaelg, Gailck"},
  {"code": "mi", "name": "Maori", "nativeName": "Te reo Māori"},
  {"code": "mr", "name": "Marathi", "nativeName": "मराठी"},
  {"code": "mh", "name": "Marshallese", "nativeName": "Kajin M̧ajeļ"},
  {"code": "mn", "name": "Mongolian", "nativeName": "монгол"},
  {"code": "na", "name": "Nauru", "nativeName": "Ekakairũ Naoero"},
  {"code": "nv", "name": "Navajo", "nativeName": "Diné bizaad, Dinékʼehǰí"},
  {"code": "nd", "name": "Ndebele North", "nativeName": "IsiNdebele"},
  {"code": "nr", "name": "Ndebele South", "nativeName": "IsiNdebele"},
  {"code": "ng", "name": "Ndonga", "nativeName": "Owambo"},
  {"code": "ne", "name": "Nepali", "nativeName": "नेपाली"},
  {"code": "se", "name": "Northern Sami", "nativeName": "Davvisámegiella"},
  {"code": "no", "name": "Norwegian", "nativeName": "Norsk"},
  {"code": "nn", "name": "Norwegian Nynorsk", "nativeName": "Norsk nynorsk"},
  {"code": "oc", "name": "Occitan (post 1500)", "nativeName": "Occitan"},
  {"code": "oj", "name": "Ojibwa", "nativeName": "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  {"code": "or", "name": "Oriya", "nativeName": "ଓଡ଼ିଆ"},
  {"code": "om", "name": "Oromo", "nativeName": "Afaan Oromoo"},
  {"code": "os", "name": "Ossetian", "nativeName": "ирон æвзаг"},
  {"code": "pi", "name": "Pali", "nativeName": "पाऴि"},
  {"code": "pa", "name": "Panjabi", "nativeName": "ਪੰਜਾਬੀ, پنجابی‎"},
  {"code": "fa", "name": "Persian", "nativeName": "فارسی"},
  {"code": "pl", "name": "Polish", "nativeName": "Polski"},
  {"code": "pt", "name": "Portuguese", "nativeName": "Português"},
  {"code": "ps", "name": "Pushto", "nativeName": "پښتو"},
  {"code": "qu", "name": "Quechua", "nativeName": "Runa Simi, Kichwa"},
  {"code": "ro", "name": "Romanian", "nativeName": "Română"},
  {"code": "rm", "name": "Romansh", "nativeName": "Rumantsch grischun"},
  {"code": "rn", "name": "Rundi", "nativeName": "KiRundi"},
  {"code": "ru", "name": "Russian", "nativeName": "русский язык"},
  {"code": "sm", "name": "Samoan", "nativeName": "Gagana faa Samoa"},
  {"code": "sg", "name": "Sango", "nativeName": "Yângâ tî sängö"},
  {"code": "sa", "name": "Sanskrit", "nativeName": "संस्कृतम्"},
  {"code": "sc", "name": "Sardinian", "nativeName": "sardu"},
  {"code": "sr", "name": "Serbian", "nativeName": "Cрпски језик"},
  {"code": "sn", "name": "Shona", "nativeName": "ChiShona"},
  {"code": "ii", "name": "Sichuan Yi", "nativeName": "ꆈꌠꉙ"},
  {"code": "sd", "name": "Sindhi", "nativeName": "सिन्धी, سنڌي، سندھی‎"},
  {"code": "si", "name": "Sinhala", "nativeName": "සිංහල"},
  {"code": "sk", "name": "Slovak", "nativeName": "Slovenčina"},
  {"code": "sl", "name": "Slovenian", "nativeName": "Slovenščina"},
  {"code": "so", "name": "Somali", "nativeName": "Soomaaliga, af Soomaali"},
  {"code": "st", "name": "Sotho, Southern", "nativeName": "Sesotho"},
  {"code": "es", "name": "Spanish", "nativeName": "Español, castellano"},
  {"code": "su", "name": "Sundanese", "nativeName": "Basa Sunda"},
  {"code": "sw", "name": "Swahili", "nativeName": "Kiswahili"},
  {"code": "ss", "name": "Swati", "nativeName": "SiSwati"},
  {"code": "sv", "name": "Swedish", "nativeName": "Svenska"},
  {"code": "tl", "name": "Tagalog", "nativeName": "Wikang Tagalog"},
  {"code": "ty", "name": "Tahitian", "nativeName": "Reo Tahiti"},
  {"code": "tg", "name": "Tajik", "nativeName": "тоҷикӣ, toğikī, تاجیکی‎"},
  {"code": "ta", "name": "Tamil", "nativeName": "தமிழ்"},
  {"code": "tt", "name": "Tatar", "nativeName": "татарча, tatarça, تاتارچا‎"},
  {"code": "te", "name": "Telugu", "nativeName": "తెలుగు"},
  {"code": "th", "name": "Thai", "nativeName": "ไทย"},
  {"code": "bo", "name": "Tibetan", "nativeName": "བོད་ཡིག"},
  {"code": "ti", "name": "Tigrinya", "nativeName": "ትግርኛ"},
  {"code": "to", "name": "Tonga (Tonga Islands)", "nativeName": "Faka Tonga"},
  {"code": "ts", "name": "Tsonga", "nativeName": "Xitsonga"},
  {"code": "tn", "name": "Tswana", "nativeName": "Setswana"},
  {"code": "tr", "name": "Turkish", "nativeName": "Türkçe"},
  {"code": "tk", "name": "Turkmen", "nativeName": "Türkmen, Түркмен"},
  {"code": "tw", "name": "Twi", "nativeName": "Twi"},
  {"code": "ug", "name": "Uighur", "nativeName": "Uyƣurqə, ئۇيغۇرچە‎"},
  {"code": "uk", "name": "Ukrainian", "nativeName": "українська"},
  {"code": "ur", "name": "Urdu", "nativeName": "اردو"},
  {"code": "uz", "name": "Uzbek", "nativeName": "Zbek, Ўзбек, أۇزبېك‎"},
  {"code": "ve", "name": "Venda", "nativeName": "Tshivenḓa"},
  {"code": "vi", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
  {"code": "vo", "name": "Volapük", "nativeName": "Volapük"},
  {"code": "wa", "name": "Walloon", "nativeName": "Walon"},
  {"code": "cy", "name": "Welsh", "nativeName": "Cymraeg"},
  {"code": "fy", "name": "Western Frisian", "nativeName": "Frysk"},
  {"code": "wo", "name": "Wolof", "nativeName": "Wollof"},
  {"code": "xh", "name": "Xhosa", "nativeName": "IsiXhosa"},
  {"code": "yi", "name": "Yiddish", "nativeName": "ייִדיש"},
  {"code": "yo", "name": "Yoruba", "nativeName": "Yorùbá"},
  {"code": "za", "name": "Zhuang", "nativeName": "Saɯ cueŋƅ, Saw cuengh"},
  {"code": "zu", "name": "Zulu", "nativeName": "isiZulu"}
];
